language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.1

script: 'bundle exec rake'

before_install:
  - wget -q http://www.rabbitmq.com/rabbitmq-signing-key-public.asc -O- | sudo apt-key add -
  - echo "deb http://www.rabbitmq.com/debian/ testing main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install rabbitmq-server
  - sudo service rabbitmq-server start
  - sleep 3
  - /usr/sbin/rrabbitmqctl add_user dev dev
  - /usr/sbin/rrabbitmqctl set_user_tags dev administrator
  - /usr/sbin/rrabbitmqctl add_vhost local
  - /usr/sbin/rrabbitmqctl set_permissions -p local dev '.*' '.*' '.*'
  - /usr/local/bin/rabbitmqadmin declare exchange --vhost=local --user=dev --password=dev name=kohawk type=topic
  - /usr/local/bin/rabbitmqadmin declare queue name=test durable=true auto_delete=false -u dev -p dev -V local
  - /usr/local/bin/rabbitmqadmin declare binding source=kohawk destination_type=queue destination=test routing_key=event.* -u dev -p dev -V local

notifications:
  email:
    recipients:
      - jeff.carley@gmail.com
    on_failure: change
    on_success: never
