language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.1

script: 'bundle exec rake'

services:
  - rabbitmq

before_script:
  - sudo /usr/sbin/rabbitmqctl add_user dev dev
  - sudo /usr/sbin/rabbitmqctl set_user_tags dev administrator
  - sudo /usr/sbin/rabbitmqctl add_vhost local
  - sudo /usr/sbin/rabbitmqctl set_permissions -p local dev '.*' '.*' '.*'
  - sudo /usr/local/bin/rabbitmqadmin declare exchange --vhost=local --user=dev --password=dev name=kohawk type=topic
  - sudo /usr/local/bin/rabbitmqadmin declare queue name=test durable=true auto_delete=false -u dev -p dev -V local
  - sudo /usr/local/bin/rabbitmqadmin declare binding source=kohawk destination_type=queue destination=test routing_key=event.* -u dev -p dev -V local

notifications:
  email:
    recipients:
      - jeff.carley@gmail.com
    on_failure: change
    on_success: never
